### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by habuild**
I hadn't read page 1 of the addon tutorial for a few months! 
I had completely missed the link to the DHCP addon addition. I could have used the example yesterday!

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @habuild, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons-example#49).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by ludeeus — COMMENTED** [review]
We should not add this here.
You should use bashio like its used in this repo <https://github.com/home-assistant/addons-example/blob/main/example/rootfs/etc/services.d/example/run>
Of use the Supervisor API to get it if you cant use it.

**Comment by habuild** [comment]
https://developers.home-assistant.io/docs/add-ons/tutorial

The link I put is from the tutorial docs. 
The reason I suggested to add it is because the first page of the tutorial is easy to skip over once you have read it, either recently or in the past.

The reason I suggested it is because the example addon is sparse for syntax examples.
A list of resources on the example would be really helpful to new people.

it would also be worth listing 
https://github.com/hassio-addons/bashio/blob/167216925b308d2e82edafc55d62eb1b04c01ff5/lib/config.sh
Although this is also a bit confusing to a new person. I had no idea if I was supposed to use the whole function or not.
 
I should use bashio like it is in the docs. But 1 line in an example addon doesn't help me alot when I started using bashio yesterday.

**Comment by frenck** [comment]
I agree with @ludeeus that this is not the right place (and debatable in correctness).

If you think our developer documentation can be improved, feel free to do so by opening a PR to our developer documentation repository.

../Frenck

**Comment by habuild** [comment]
I agree in hindsight. Although I do think it would be reasonable to have some quick links on the example readme repo. It was more of a suggestion to be honest, because I had totally missed it in the docs and it would have been useful today.

An as alternative I do think the addon tutorial could use a "useful links and examples" as the last page. It should be less verbose than the actual tutorial just working examples and quick links. Although I don't really have much in the way of experience to offer there.

**Pull request closed without merging**
